### ISSUE TITLE
v1 docs have disappeared

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#10]
From #4:

1.30 is not marked as deprecated on the current docs, but doesn't appear to be preserved and redirects don't work. Are we just giving up on 1.30 entirely? e.g. https://www.pantsbuild.org/v1.30/docs -> https://docs.pantsbuild.org/v1.30/docs

**Comment by benjyw** [comment]
We should still host the frozen v1 docs though? I wouldn't expect that to
be broken unless it's due to configuration changes on GitHub

**Comment by huonw** [comment]
I see. Can you find a link to the slack discussion for reference?

Agreeing with @benjyw: I think it'd be good to make sure there's at least an static archived copy. Potentially we could verify if snapshots on web.archive.org work well enough?

**Comment by thejcannon** [comment]
Ok I can see if we can host it as well

**Comment by benjyw** [comment]
It was already hosted on GitHub pages, I'm not sure why we'd need to do
anything differently

**Comment by benjyw** [comment]
My guess is that this is due to some config issue on the GitHub pages side

**Comment by thejcannon** [comment]
Actually, yeah. What relation does the readme docs have to https://v1.pantsbuild.org/?

**Comment by benjyw** [comment]
None at all. This is why I suspect that the problem is related to GitHub
pages config due to having multiple subdomains or something.

**Comment by huonw** [comment]
Ah, given we have https://v1.pantsbuild.org, I guess we could have this new site defer to that, rather than try to rehost the v1 docs too? It looks like it's a bit different to the readme docs though...

Assuming we do that, maybe this is a matter of:

1. setting up appropriate redirects somehow. I can think of three options:
  a. doing precise redirects for every https://www.pantsbuild.org/v1.x/docs/... page
  b. doing an imprecise redirect for every page to the top-level https://v1.pantsbuild.org
  c. not doing any static redirects for v1 and having dynamic behaviour on the 404 page, e.g. detect the URL has a `v1.` in it and either do the redirect dynamically or suggest a `site:https://v1.pantsbuild.org/ <other parts of the url>` search
2. providing static links to it (e.g. in the "All versions" version selector, if possible?)

Thoughts?

**Comment by benjyw** [comment]
I believe this conversation is complicating a simple problem:

1) The v1 docs are hosted in some GitHub repo and published via GH Pages,
to v1.pantsbuild.org.

2)The new docs are hosted in some other GitHub repo, and also published via
GH Pages, to docs.pantsbuild.org.

My hypothesis is that some GH config that was needed to make 2) happen
inadvertently destroyed whatever GH Pages routing made 1) happen. I am
hoping that fixing this is just a matter of config - finding out how to
host two GH Pages repos at two different subdomains.

**Comment by benjyw** [comment]
Ooooooooh! My misunderstanding (I'm afk)

In that case, I think we can just point to the first page of those
statically from somewhere in the intro text... doesn't have to be more
clever than that.

**Comment by thejcannon** [comment]
> In that case, I think we can just point to the first page of those statically from somewhere in the intro text... doesn't have to be more clever than that.

Specifically, what do you mean by that? Continue with `docs.pantsbuild.org` not containing any v1 docs, and instead link to `v1.pantsbuild.org` somewhere on the landing page? (I.e. https://docs.pantsbuild.org/)

**Comment by thejcannon** [comment]
> Ah, given we have [v1.pantsbuild.org](https://v1.pantsbuild.org), I guess we could have this new site defer to that, rather than try to rehost the v1 docs too? It looks like it's a bit different to the readme docs though...
> 
> Assuming we do that, maybe this is a matter of:
> 
>     1. setting up appropriate redirects somehow. I can think of three options:
>        a. doing precise redirects for every [pantsbuild.org/v1.x/docs](https://www.pantsbuild.org/v1.x/docs/)... page
>        b. doing an imprecise redirect for every page to the top-level [v1.pantsbuild.org](https://v1.pantsbuild.org)
>        c. not doing any static redirects for v1 and having dynamic behaviour on the 404 page, e.g. detect the URL has a `v1.` in it and either do the redirect dynamically or suggest a `site:https://v1.pantsbuild.org/ <other parts of the url>` search
> 
>     2. providing static links to it (e.g. in the "All versions" version selector, if possible?)
> 
> 
> Thoughts?

1. I can't say I have enough of a preference here really. if someone wants to put the work into a better UX for v1 redirects, cool. Otherwise I'll take whatever
2. Yeah probably a good idea either way

**Comment by benjyw** [comment]
Yes, exactly just this. Link from the landing page and move on.

**Comment by thejcannon** [comment]
I did a little bit of scripting on top of the Readme API for page views over the last month...

```
"1.27": 34
"1.28": 30
"1.29": 263
"1.30": 222
"2.0": 215
"2.1": 440
"2.2": 185
"2.3": 79
"2.4": 158
"2.5": 150
"2.6": 195
"2.7": 117
"2.8": 445
"2.9": 114
"2.10": 98
"2.11": 159
"2.12": 182
"2.13": 130
"2.14": 146
"2.15": 382
"2.16": 422
"2.17": 1175
"2.18": 43907
"2.19": 752
```

So ~550 hits for v1, representing a hair over 1% of hits.

**Comment by thejcannon** [comment]
To be clear, 1% is more than I was hoping for, but I think low enough I could honestly go either way.

**Comment by benjyw** [comment]
We still have v1.pantsbuild.org to cover those 1% no?

**Comment by benjyw** [comment]
If this brings any v1 users out of the woodwork, we can see about upgrading them, or giving them the opportunity to work on dealing with hosting the old docs (or sponsoring it).

**Comment by thejcannon** [comment]
Good idea. I can scrape them before we shut down the readme site if/when we plan on doing that
