### ISSUE TITLE
Inappropriate h1 unlinkable & missing from table of contents on "targets" page

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#112]
https://www.pantsbuild.org/2.19/docs/using-pants/key-concepts/targets-and-build-files has various headings that aren't able to be linked and don't appear in the table of contents. It appears to be the h1 headings. 

This may due to violating the "[Avoid using multiple &lt;h1&gt; elements on one page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#avoid_using_multiple_h1_elements_on_one_page)" guideline.

Potentially this is just inherited from our old docs, and docusaurus handles it different to readme, or maybe it's a bug in the generator?

**Comment by huonw** [comment]
> Potentially this is just inherited from our old docs, and docusaurus handles it different to readme, or maybe it's a bug in the generator?

Yes, the old docs use `<h1>` too, e.g. https://old.pantsbuild.org/docs/targets#build-files

**Comment by thejcannon** [comment]
Ah, this actually was in the conversion script, however it only worked on `#` markdown headers.

`2.20.x/docs/using-pants/key-concepts/targets-and-build-files.mdx` uses `====` underlined headers.

Should be easy to fix in-place though.

```python
def replace_headers(text):
    lines = text.splitlines()
    in_codeblock = False
    has_h1_header = False
    for index, line in enumerate(lines):
        if line.startswith("```"):
            in_codeblock = not in_codeblock
            continue

        if line.startswith("# ") and not in_codeblock:
            has_h1_header = True

        if line.startswith("#") and not in_codeblock and has_h1_header:
            lines[index] = "#" + line
    return "\n".join(lines)
```

**Comment by thejcannon** [comment]
I wonder if we can't try and catch this in CI
