### ISSUE TITLE
Misformed links from Google search to Pants docs site ampersand expansion

### ISSUE THREAD

**Issue by danny-todd-oxb** [pantsbuild/pantsbuild.org#122]
**Describe the bug**
For some links when opening from Google search results, ampersands are expanded incorrectly (& -> &amps;) so the resulting opened page 404s. 

e.g. on an incognito window in Chrome (link: [https://www.pantsbuild.org/2.18/docs/using-pants/remote-caching-&amp;-execution](https://www.pantsbuild.org/2.18/docs/using-pants/remote-caching-&amp;-execution))
![image](https://github.com/pantsbuild/pants/assets/101182561/4714f926-2ba1-42e2-9ce5-3be5418fca81)

Relevant Slack thread: https://pantsbuild.slack.com/archives/C046T6T9U/p1705335830401029

**Comment by thejcannon** [comment]
Odd, that link works for me :stuck_out_tongue: on both Firefox and Chrome

**Comment by huonw** [comment]
In #127, I propose side-stepping the issue by just removing the `&`s from the URLs.
