### ISSUE TITLE
pantsbuild.org/versions has many broken links

### ISSUE THREAD

**Issue by foobar-coder** [pantsbuild/pantsbuild.org#147]
**Describe the bug**

Many links on the versions page lead to a 404 page

**Additional info**

Examples:

https://www.pantsbuild.org/2.17.x/docs/introduction/how-does-pants-work

https://www.pantsbuild.org/2.4.x/docs/introduction/how-does-pants-work

**Comment by foobar-coder** [comment]
@thejcannon 

> would you be interested in a little PR?

I could review one for sure. 

But I don't know enough about your codebase to fix this and open one myself

**Comment by foobar-coder** [comment]
> It's the ".x" in the URL

FWIW, it's not just the `x`

Example:

<https://www.pantsbuild.org/2.6/docs/introduction/how-does-pants-work>
<https://www.pantsbuild.org/2.6/docs/>

**Comment by huonw** [comment]
Thanks @foobar-coder !

The page in question is https://github.com/pantsbuild/pantsbuild.org/blob/main/src/pages/versions/index.md

Good catch with those extra problems, it looks like there's a two sets of fixes to make:

- remove the `.x`s
- change the entry point links for versions before 2.10

| versions | starting page | example |
|---|---|---|
| 2.10 - 2.19 | `docs/introduction/how-does-pants-work` ✅ | https://www.pantsbuild.org/2.10/docs/introduction/how-does-pants-work |
| 2.6 - 2.9 | `docs/learn-about-pants/welcome-to-pants` | https://www.pantsbuild.org/2.6/docs/learn-about-pants/welcome-to-pants |
| 2.0 - 2.5 | `docs/introduction/welcome-to-pants` | https://www.pantsbuild.org/2.0/docs/introduction/welcome-to-pants |

**Comment by huonw** [comment]
Oh, hm, versions 2.10 - 2.19 have a `welcome-to-pants` page too (e.g. https://www.pantsbuild.org/2.10/docs/introduction/welcome-to-pants), and that's the default one (e.g the "Docs" link in the navbar is to https://www.pantsbuild.org/2.18/docs/introduction/welcome-to-pants), but the versions page links to https://www.pantsbuild.org/2.18/docs/introduction/how-does-pants-work instead. I've adjusted the table to suggest they need to be updated too.
