### ISSUE TITLE
Don't show "Search coming soon" while it's pending

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#15]
From #4:

Maybe we could just remove the "search coming soon" text completely: it gives me geocities vibes, where everything was always 🚧 under construction 🚧/coming soon and never actually did 😄 Once we have search, we can then just restore it.

**Comment by thejcannon** [comment]
For the record, I applied for Algolia DocSearch, and am just waiting to hear back

**Comment by huonw** [comment]
Cool, I opened #26 to track adding search explicitly.
