### ISSUE TITLE
"Getting started" docs show two levels of expanders

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#16]
From #4:

There's two levels of expanders for "Getting started": https://docs.pantsbuild.org/2.18.x/docs/getting-started/getting-started
   <img width="300" alt="image" src="https://github.com/pantsbuild/pantsbuild.org/assets/1203825/ded76473-f0aa-4866-b352-2a36f09005e8">

**Comment by thejcannon** [comment]
To be fair, this is how it's structured in the existing docs site...

![Screenshot from 2023-12-30 06-45-45](https://github.com/pantsbuild/pantsbuild.org/assets/3956745/69196c7a-ffe3-45c1-823d-0ef586d28f59)

**Comment by huonw** [comment]
Ah, I see... just fewer clicks/less obvious with how readme does the section headers.

**Comment by thejcannon** [comment]
We can and should fix this, just noting that it's inherited from the current docs site
