### ISSUE TITLE
Optimise reference "list" pages (goals, subsystems etc.)

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#17]
From #4:

The reference listing page for goals etc. seems to have large cards for each item, all with content `---`. Is it possible to switch to either switch to a (denser) plain list, and/or put real content in those cards? https://docs.pantsbuild.org/2.18.x/reference/goals
   <img width="240" alt="image" src="https://github.com/pantsbuild/pantsbuild.org/assets/1203825/0ba7cd7d-196e-45f7-abe3-60ec516559a3">

**Comment by thejcannon** [comment]
It is possible to customize these, see Docusarus's own docs: https://docusaurus.io/docs/category/guides

The question becomes how easy that is to do with autogenerated indexes. I imagine that the per-page header metadata would be where it's easy to customize without ruining the autogenerated nature

**Comment by huonw** [comment]
Looks great now 👍 

![image](https://github.com/pantsbuild/pantsbuild.org/assets/1203825/0d3fbcde-f011-4a4d-9a2f-f5cdef604b05)
