### ISSUE TITLE
Ruff reference doc has wrong backend

### ISSUE THREAD

**Issue by sureshjoshi** [pantsbuild/pantsbuild.org#219]
Introduced here as `pants.core`

https://github.com/pantsbuild/pantsbuild.org/commit/7a10b3835332e3e72703f845ee3dca3bfa010d4f#diff-d6072f2018f9be862e7b9dc396943d363f4f696bbe2b3737325dd2ce4bbced76

**Comment by sureshjoshi** [comment]
Not sure where that info comes from - I thought it was generated from Pants
https://github.com/pantsbuild/pants/issues/20981

**Comment by huonw** [comment]
Yeah, it entirely comes from pants. I'm going to close this in favour of the Pants issue, since that's the source of truth. As extra confirmation it's not something about this repo's rendering of the docs, `pants help ruff` CLI has the same problem:

```
`ruff` subsystem options
------------------------

The Ruff Python formatter (https://github.com/astral-sh/ruff).
 
Activated by pants.core
...
```
