### ISSUE TITLE
Scraped prose docs don't match structure of pants repos, thus sync PRs have spurious changes

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#34]
It seems the content scraped from readme doesn't match the structure of what's in the Pants repo, which means the doc syncing PRs don't fit into that smoothly: e.g. #32 has a massive diff stat, despite being a no-op update, theoretically (readme should be showing version 2.18.1 already).

I imagine these differences may result in mis-rendered docs, if they were merged.

Notable differences in prose docs:

| # | PR behaviour | main behaviour | PR link | `main` link |
|---|---|---|---|---|
|1 | content is contained within `docs/markdown/` directory | just `docs/` | [PR](https://github.com/pantsbuild/pantsbuild.org/tree/f7004fbcc5e386abf998603de17a839546cef4c2/versioned_docs/version-2.18.x/docs) | [main](https://github.com/pantsbuild/pantsbuild.org/tree/6185bd4d59545d3f5f0e473939eaff743e3f0054/versioned_docs/version-2.18.x/docs) |
|2| directory names are Sentence Case | snake-case | [PR](https://github.com/pantsbuild/pantsbuild.org/tree/f7004fbcc5e386abf998603de17a839546cef4c2/versioned_docs/version-2.18.x/docs/markdown/Ad-Hoc%20Tools) | [main](https://github.com/pantsbuild/pantsbuild.org/tree/6185bd4d59545d3f5f0e473939eaff743e3f0054/versioned_docs/version-2.18.x/docs/ad-hoc-tools) | 
|3| file names use the slug | use title | [PR](https://github.com/pantsbuild/pantsbuild.org/blob/f7004fbcc5e386abf998603de17a839546cef4c2/versioned_docs/version-2.18.x/docs/markdown/Ad-Hoc%20Tools/adhoc-tool.md) | [main](https://github.com/pantsbuild/pantsbuild.org/blob/6185bd4d59545d3f5f0e473939eaff743e3f0054/versioned_docs/version-2.18.x/docs/ad-hoc-tools/integrating-new-tools-without-plugins.mdx) |
|4| no `_category_.json` files | yes files | [PR](https://github.com/pantsbuild/pantsbuild.org/tree/f7004fbcc5e386abf998603de17a839546cef4c2/versioned_docs/version-2.18.x/docs/markdown/Ad-Hoc%20Tools) | [main](https://github.com/pantsbuild/pantsbuild.org/tree/6185bd4d59545d3f5f0e473939eaff743e3f0054/versioned_docs/version-2.18.x/docs/ad-hoc-tools) | 

Potentially others: would be easiest to identify once we solve more of those to reduce the number of diffs to filter through.

(See https://github.com/pantsbuild/pantsbuild.org/issues/37 for differences in the reference docs)

**Comment by huonw** [comment]
Are we expecting to resolve 1 and 4 via this too? i.e. we're going to change the directory nesting structure (in addition to the raw contents) and add the new json files, in the pants repo?

**Comment by huonw** [comment]
Also, do you reckon we avoid changing directory names to have spaces in them (2)? It makes for simpler adhoc tooling if we can avoid file/directory names with spaces in them (e.g. one-off script to process a specific set of files... simpler if one can cut a corner by not being forced to handle paths with spaces in them).

**Comment by thejcannon** [comment]
I would expect all 4 to be fixed once we merge this repo back into the pants repo

**Comment by thejcannon** [comment]
FWIW I tested the sync script using a branch of the pants repo with these changes already merged in it, then made a simple change.

The sync script made a PR with just the single change in it.

**Comment by huonw** [comment]
As in, yes, we're going to change the nesting structure and add the new JSON files in the pants repo?

What do you think about the question about spaces in file paths?

**Comment by thejcannon** [comment]
Yes to changing structure, adding JSON, and removing spaces.

If it helps, imagine each nested docs/ dir in this repo as a snapshot of the pants repo, where branches there are directories here.

The docs dirs here are just glorified codegen, where the code is generated by just copying the contents.

So what you see here is what will be over there after migration.

Does that make sense?

**Comment by thejcannon** [comment]
Marking as complete with https://github.com/pantsbuild/pants/pull/20395
