### ISSUE TITLE
What's the plan for the old blog.pantsbuild.org site?

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#36]
There's a bunch of content currently hosted at https://blog.pantsbuild.org, some of which is often linked a year and a half after it was written (e.g. https://blog.pantsbuild.org/optimizing-python-docker-deploys-using-pants/).

With the new site seeming to try to subsume the blog right away, should we be redirecting its URLs too? Or can we potentially cut scope for the initial roll-out and leave https://blog.pantsbuild.org as is for now and then handle that as follow-up (i.e. get the main switch-over out sooner)?

**Comment by thejcannon** [comment]
Can we just deploy a static site using another GitHub repo and GitHub pages that just redirects.

And then _thatll_ be blog.pantsbuild.org when we're ready.

**Comment by huonw** [comment]
So to be clear: in the short term, for the main doc/website switchover, we leave blog.pantsbuild.org as is?

**Comment by thejcannon** [comment]
Yeah we can just turn off the blog for now (or leave it) and then fast-follow with the blog switchover

**Comment by thejcannon** [comment]
OK I have https://github.com/thejcannon/blog.pantsbuild.org which we can transfer to `pantsbuild` org, then configure DNS for.

https://thejcannon.github.io/blog.pantsbuild.org/
https://thejcannon.github.io/blog.pantsbuild.org/pants-2-15
(etc...)

**Comment by huonw** [comment]
Nice! It looks like https://blog.pantsbuild.org/pants-2-18-0-is-released/ is still the original version, so I assume we're still working out the details of this switch? Is there something I can do to help?

**Comment by thejcannon** [comment]
Yeah, @benjyw is currently in Columbia, and I don't feel comfortable doing the DNS switch myself without a buddy.

Hang tight, we're almost there.

**Comment by huonw** [comment]
The redirects seem to be working smoothly, and https://github.com/pantsbuild/pantsbuild.org/pull/146 completes it! 🎉
