### ISSUE TITLE
Auto-synced reference docs don't match checked-in code, thus sync PRs have spurious changes

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#37]
It seems the current content for the reference docs (scraped from readme?) doesn't match those generated by the auto-sync PR, which means the doc syncing PRs don't fit into that smoothly: e.g. #32 has a massive diff stat, despite being a no-op update, theoretically (readme should be showing version 2.18.1 already).

I imagine these differences may result in mis-rendered docs, if they were merged.

Notable differences in reference/generated docs:

| # | PR behaviour | main behaviour | PR link | `main` link |
|---|---|---|---|---|
|1| only a few subsystems (e.g. no `add-trailing-comma`) | lots of subsystems | [PR](https://github.com/pantsbuild/pantsbuild.org/tree/f7004fbcc5e386abf998603de17a839546cef4c2/versioned_docs/version-2.18.x/reference/subsystems) | [main](https://github.com/pantsbuild/pantsbuild.org/tree/6185bd4d59545d3f5f0e473939eaff743e3f0054/versioned_docs/version-2.18.x/reference/subsystems) |
|2| spacing differences | - | [PR diff of `anonymous-telemetry.mdx`](https://github.com/pantsbuild/pantsbuild.org/pull/32/files#diff-8539553f255b37b9d6ae0fced75385e6ca4166f0f4cd05e1e83469ee52c862d5) | (see diff) |
|3| escaping etc. differences | - | [PR diff of `target.mdx`](https://github.com/pantsbuild/pantsbuild.org/pull/32/files#diff-f167a31ae9026b13c3744ce353e50d853fa99710381e30a449773758e78ca7b0) | (see diff) |
|4| no related subsystems in goals | - | [PR diff of `check.mdx`](https://github.com/pantsbuild/pantsbuild.org/pull/32/files#diff-0ef5502578202a722dd7a62dd567c502f61bc3c2658c86ba3a3031b05d46d849) | (see diff) |
|5| `default_repr` differences | - | [PR diff of `global-options.mdx`](https://github.com/pantsbuild/pantsbuild.org/pull/32/files#diff-53d8f10c04de6d0452ceda55c6708e8cf2e297b1f4b5f508f48b879f5454fe8c) | (see diff) |

Potentially others: would be easiest to identify once we solve more of those to reduce the number of diffs to filter through.

(See #34 for differences in the prose docs)

**Comment by thejcannon** [comment]
This one is known, the templates were recently updated to use `mustache` and JS instead of `Jinja` and Python.

Not hard to re-gen though.

**Comment by huonw** [comment]
I think it is hard to regen at the moment. Also, at least the first of these doesn't seem like a template issue, and maybe one or two of the others?

**Comment by thejcannon** [comment]
OK 1 seems to be a misunderstanding between @kaos and I about how `help-all` works with no backends enabled. I'll split it into another issue for tracking.

(See [Slack](https://pantsbuild.slack.com/archives/C0D7TNJHL/p1704227821488689?thread_ts=1703265536.163199&cid=C0D7TNJHL))

**Comment by thejcannon** [comment]
Ok after https://github.com/pantsbuild/pantsbuild.org/pull/43 is in, we can re-gen which should take care of templating issues,

**Comment by huonw** [comment]
I tried it in #50 and it looks like it's not that simple, e.g. 4 and 5 aren't fixed and may cause problems.
