### ISSUE TITLE
Day-of Tasks (e.g. "No turning back" tasks)

### ISSUE THREAD

**Issue by thejcannon** [pantsbuild/pantsbuild.org#40]
Thought-dumping the "No Turning Back" tasks here:

- subdomain
  - Have @benjyw update the DNS
  - Update the DNS config on GitHub
  - Update URL in `docusaurus.js`
- Updating https://github.com/pantsbuild/pants:
  - (For each relevant branch)
  - Sync the content to readme.com
  - Re-generate the entire docs site for that version
  - PR it here
  - PR it on the repo under the `docs/` path
- Search
  - In Algolia crawler, edit the crawler settings to crawl the new URL
  - See if we can wipe the index
  - Trigger a new crawl

- update maintainers docs with any relevant new steps (e.g. when cutting a new version)

**Comment by huonw** [comment]
> PR it on the repo under the docs/ path


Is it easy to do a demo/test of this in the pants repo? So we can be sure it works as we wish?

**Comment by thejcannon** [comment]
Yeah? It's just replacing the `docs` directory with the similarly named one from the relevant directory here.

Not terribly exciting 😅

**Comment by thejcannon** [comment]
I have started the docs regeneration and blasting

**Comment by thejcannon** [comment]
https://www.pantsbuild.org
