### ISSUE TITLE
Search doesn't find any results

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#45]
Currently, using the search gives no results ever. For instance, searching for "pants":

![image](https://github.com/pantsbuild/pantsbuild.org/assets/1203825/341b81ba-0a1a-4d24-a71f-a2dedf79049c)

This is potentially expected (e.g. waiting for Algolia to index), but just filing to have a record/place to discuss if it lasts longer than expected.

**Comment by huonw** [comment]
Hm, #61 seems to be deployed (e.g. the sitemap https://docs.pantsbuild.org/sitemap.xml references the correct URLs), but search still finds nothing. Do we need to re-trigger an indexing on on the algolia side @thejcannon?

(On that note, is the algolia log-in shared somehow? and/or keyed off the @WorkerPants email?)

**Comment by thejcannon** [comment]
I reran the index and no dice. Probably an issue with the config

**Comment by thejcannon** [comment]
Search works!  https://docs.pantsbuild.org/search?q=python

Turns out the default Algolia search config client-side (set up by Docusaurus) includes certain facets that our index wasn't configured to support. After adding those facets, we're searching!
