### ISSUE TITLE
Proposal: skip the .x in URLs/dropdowns

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#47]
The `2.18.x` version signifier seems like it could easily be `2.18` with identical meaning for users, but results in slightly neater URLs and simpler drop-downs:

![image](https://github.com/pantsbuild/pantsbuild.org/assets/1203825/aed9019d-e9d3-4b6b-ad31-74e76455253a)

(Labelled for `Switch-over` because this'll change URLs.)

**Comment by thejcannon** [comment]
I like this. :+1:
