### ISSUE TITLE
Support redirecting for URL fragments (page subheadings), especially `code...code` in target fields

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#6]
From #4:

It looks like the heading fragments differ for some items, e.g. https://www.pantsbuild.org/v2.19/docs/reference-deploy_jar#coderesolvecode links to the resolve field specifically, while the redirect https://docs.pantsbuild.org/2.19.x/reference/targets/deploy_jar#coderesolvecode does not. Can we run client side JS easily (as part of the redirect)? If so, I guess we could replace `codeXYZcode` with `XYZ`, and maybe that handles most cases: the only ones I could find are the field headings for a target.

**Comment by thejcannon** [comment]
My own 2c is that since the page redirect works, the fragment part isn't as vital. Id honestly be ok if the (already wonky, wtf?!) fragments didn't anchor.

That being said, it might be easy to fix and is worth a shot. 

The only thing is I wouldn't want this client-side JS having to run on _every_ page (every redirect is OK because we know we're redirecting) but if someone visits the page with a new URL id hate to run this code for it to do nothing

**Comment by thejcannon** [comment]
I don't see any mention of fragments in https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects. So we might have to get our hands dirty

**Comment by huonw** [comment]
Yeah, looks like the template it uses doesn't support transforming the fragment or custom code: https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-plugin-client-redirects/src/templates/redirectPage.template.html.ts

So, as you say, we have options:

1. Don't bother, and people can find what they're looking for themselves assuming they have enough context (not just "use this field $link")
2. Generate the redirects ourselves 
3. Enhance the plugin to allow a dynamic transformation in the template
4. A short snippet of JS on every page to fix it up retroactively... I don't think this is that bad, as it's a progressive enhancement (if it fails completely, the page will behave as 1.) and very short/efficient "if regex matches, replace fragment"

1 would be acceptable for initial roll-out, I think, ie this isn't a blocker.

**Comment by thejcannon** [comment]
Another option is to generate, but not render the display for, headers that have the "bad" fragment as an anchor (on all the existing reference docs, but none of the new ones going forward)

**Comment by huonw** [comment]
Huh, yeah, that's a good idea too. I like it as an option.
