### ISSUE TITLE
Ensure 404 page is visible for all wrong URLs

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#7]
From #4:

A "404" shows the menu structure but no actual content: https://docs.pantsbuild.org/xyz/abc. It'd be good to have some sort of real content describing the problem.

**Comment by huonw** [comment]
Ah, broken URLs under a version do show a useful 404: https://docs.pantsbuild.org/2.19.x/abc ... so this is more about making sure that's always shown.

**Comment by thejcannon** [comment]
Also, for reference here's the existing 404 page: https://www.pantsbuild.org/docs/foo

**Comment by thejcannon** [comment]
OK so spinning up a new docs site, it _does_ 404 correctly. So far I haven't been able to deduce what's different about our little slice of heaven and a fresh docs site that'd cause this.

**Comment by thejcannon** [comment]
OK I've narrowed it down to what appears to be "disableVersioning: true" making the top-level 404 page be blank...

**Comment by thejcannon** [comment]
Alright, so poking at it more, this just looks like a Docusuarus bug: https://github.com/facebook/docusaurus/issues/9688
