### ISSUE TITLE
Ensure people aren't editing prose docs in this repo

### ISSUE THREAD

**Issue by thejcannon** [pantsbuild/pantsbuild.org#76]
As @benjyw pointed out in the Pants meetup was that it's not completely obvious people shouldn't edit certain docs in this repo (`/docs` docs)

We should add a PR CI check for this (or similar automation)

**Comment by huonw** [comment]
Potential check: if a PR changes the prose docs or `help-all.json`, it must have a particular label (e.g. `automation:sync-docs`) that the @WorkerPants PRs automatically add (and if a human knows what they're doing and needs to update those files, they can add the label manually too).

**Comment by thejcannon** [comment]
Yeah that's loosely what I had in mind. Fail the build and also give a helpful comment pointing to the pants repo
