### ISSUE TITLE
Make the 404 page smart, e.g. search, "Did you mean"

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#88]
Our not found page is currently static, but typically we can infer things from the URL that allow us to do more than just 'block' a user, e.g.

- break the URL up into parts and do a search: `pantsbuild.org/something-here` could turn into a search for `something here`, as would `pantsbuild.org/docs/v2.19/something-here` (i.e. ignore obvious 'cruft' like `docs`, `reference` or version slugs)
- bonus, iterating on #10: if it contains `/v1.`, they're likely looking for v1 docs so direct to v1.pantsbuild.org (potentially including a `site:https://v1.pantsbuild.org` search) (https://github.com/pantsbuild/pantsbuild.org/pull/87#issuecomment-1888007661)

Example: https://doc.rust-lang.org/stable/std/tree

**Comment by thejcannon** [comment]
It doesn't even have to be dynamic. We could keep it static and just have a handful of suggestions.

(Not saying dynamic isn't nicer, but if it's too complex I'd settle for static 🙂)
