### ISSUE TITLE
Show pants.toml snippet for global/goal/subsystem options, like current site

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pantsbuild.org#9]
From #4:

The current 2.19.x reference docs show a TOML snippet, e.g. https://www.pantsbuild.org/v2.19/docs/reference-add-trailing-comma, but the new ones don't show this https://docs.pantsbuild.org/2.19.x/reference/subsystems/add-trailing-comma . Is that expected?

<img width="351" alt="image" src="https://github.com/pantsbuild/pantsbuild.org/assets/1203825/20abc8b7-ac9e-4306-9224-a623ab3fbed9">

**Comment by thejcannon** [comment]
I mustve started this venture before that change was introduced. We have the ability to update _all_ reference docs with certain changes (which I'd argue is a great thing).

I suspect if we update the Option React component we can roll this out easily.

**Comment by huonw** [comment]
Nice. 

I started investigating this and I think we'll need to port https://github.com/pantsbuild/pants/pull/19718 (and https://github.com/pantsbuild/pants/pull/20345) either to the component or, better, to `generate.js`.

**Comment by huonw** [comment]
Ah, AIUI, it may be somewhat awkward to do broad-sweeping regeneration like this: #29 for discussion.
